---
name: Build image with Multi-Platform

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU # Build images to support multi-platforms
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx # Extend image building capabilities
        uses: docker/setup-buildx-action@v4 

      - name: Login to Docker Hub # Login to DockerHub
        uses: docker/login-action@v4 
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build # Build Image
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }} # Do not push on pull_request, only push and workflow_dispatch (manual)
          tags: danny0908/mywebapp:01 # Tag this build on dockerhub

          cache-from: type=gha # import previously saved layers from GitHub Actions cache
          cache-to: type=gha,mode=max # export new/updated layers back to GitHub Actions cache
          # type=gha selects the GitHub Actions cache backend
          # mode=max exports all intermediate layers, not just the minimal set.

          platforms: linux/amd64,linux/arm64,linux/arm/v7 # Add support for AMD/Intel/ARM for linux. For windows containers: windows/amd64

